# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1126, 905)
        self.menu_frame = QtWidgets.QFrame(Form)
        self.menu_frame.setGeometry(QtCore.QRect(10, 20, 231, 671))
        self.menu_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_frame.setObjectName("menu_frame")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.menu_frame)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 0, 191, 141))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pcd_show_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pcd_show_btn.setObjectName("pcd_show_btn")
        self.verticalLayout.addWidget(self.pcd_show_btn)
        self.pcd_loop_show_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pcd_loop_show_btn.setObjectName("pcd_loop_show_btn")
        self.verticalLayout.addWidget(self.pcd_loop_show_btn)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.log_frame = QtWidgets.QFrame(Form)
        self.log_frame.setGeometry(QtCore.QRect(10, 710, 1101, 191))
        self.log_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.log_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.log_frame.setObjectName("log_frame")
        self.label_2 = QtWidgets.QLabel(self.log_frame)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 1081, 171))
        self.label_2.setObjectName("label_2")
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setGeometry(QtCore.QRect(280, 20, 831, 661))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.page)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 821, 661))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.pcd_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.pcd_layout.setContentsMargins(0, 0, 0, 0)
        self.pcd_layout.setObjectName("pcd_layout")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)

        self.retranslateUi(Form)
        self.pcd_show_btn.clicked.connect(Form.select_pcd_and_show) # type: ignore
        self.pcd_loop_show_btn.clicked.connect(Form.loop_pcd_show) # type: ignore
        self.pushButton.clicked.connect(Form.point_cluster) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pcd_show_btn.setText(_translate("Form", "点云显示"))
        self.pcd_loop_show_btn.setText(_translate("Form", "点云轮播"))
        self.pushButton.setText(_translate("Form", "点云差分"))
        self.label_2.setText(_translate("Form", "日志区域"))
